### PR TITLE
fix: CSS full height background

### PR DESCRIPTION
**Pull request by kassim**
Addresses the issue mentioned here https://github.com/turbolinks/turbolinks-android/issues/43
Caused by the layout params of the WebView not having been set

### CODE REVIEW

**Comment by chamnap** [comment]
I have similar problem with the height as well, where the content's height is smaller than the webview's height. Hope this PR will fix it.

**Comment by ruudschuurmans** [comment]
@chamnap yep this PR will fix that! :) We've encountered the same problem.

**Comment by risinglf** [comment]
thanks for this fix! 

Why not merge this PR?

**Comment by lateplate** [comment]
@kassim Thanks for this! I'll pull and try it out to ensure there are no other side effects (not expecting any).

A couple very minor suggestions:
1. Move the layout code to its own private method, and call it from `createWebView()`
1. Please rebase/squash your commits into one commit so we can keep the commit history clean (the updating build tools and subsequent revert in particular).

Thanks!

**Comment by kassim** [comment]
new PR https://github.com/turbolinks/turbolinks-android/pull/63

**Pull request closed without merging**
