### PR TITLE
make sure the getDefault method return a session that turbolinksIsReady is true

### PR DESCRIPTION
**Pull request by h1u2i3**

### CODE REVIEW

**Comment by h1u2i3** [comment]
sometime when we open the app and then the TurbolinksSession initialize, if we switch to some other activity before this TurbolinksSession inject the TurbolinksNative interface, and when switch back and use the same TurbolinksSession, it always show nothing.

**Comment by h1u2i3** [comment]
Sometime when we first get the session from `TurbolinksSession.getDefault()` and visit some location, if we do something else and finish this activity, then when use the session next time, it can cause infinite refresh unless we reopen the app.

**Comment by lateplate** [comment]
I don't think that nulling out the defaultInstance based on `turbolinksIsReady()` should be necessary. The [checks in the visit() method](https://github.com/turbolinks/turbolinks-android/blob/master/turbolinks/src/main/java/com/basecamp/turbolinks/TurbolinksSession.java#L267-L274) should catch the scenarios and allow a cold boot (thus setting turbolinksIsReady) if necessary.

Did you have a reproducible scenario I could look into? There certainly could be an issue, but I personally haven't been able to reproduce it. 

Thanks!

**Comment by h1u2i3** [comment]
@lateplate , I find out that the 1.0.1 has fix the problem. So this pull request can be closed. Thanks for your response.

**Pull request closed without merging**
